source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

source/api/urls.py
from django.urls import path
from .views import AddFriendView, UnFriendView

app_name = 'api'


urlpatterns = [
    path('user/<int:pk>/addfriend/', AddFriendView.as_view(), name='addfriend'),
    path('user/<int:pk>/unfriend/', UnFriendView.as_view(), name='unfriend'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import UserListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include('api.urls')),
    path('', UserListView.as_view(), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import MessageCreateView, MessageBoxView, IncomingMessagesListView, OutcomingMessagesListView,\
    MessageDetailView

app_name = 'webapp'


urlpatterns = [
    path('accounts/<int:pk>/messages/send/', MessageCreateView.as_view(), name='message_create'),
    path('messages/', MessageBoxView.as_view(), name='message_box'),
    path('messages/inbox/', IncomingMessagesListView.as_view(), name='messages_incoming'),
    path('messages/outbox/', OutcomingMessagesListView.as_view(), name='messages_outcoming'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Friend(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name='User', related_name='friends',
                             on_delete=models.CASCADE)
    target_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                    verbose_name='Friend')


class Message(models.Model):
    sender = models.ForeignKey(get_user_model(), verbose_name='Sender', related_name='messages',
                               on_delete=models.CASCADE)
    receiver = models.ForeignKey(get_user_model(), verbose_name='Receiver', on_delete=models.CASCADE)
    text = models.TextField(max_length=500, verbose_name='Text')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

source/webapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404

from webapp.models import Message


class MessageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        receiver_pk = kwargs.pop('receiver_pk')
        sender_pk = kwargs.pop('sender_pk')
        self.sender = get_user_model().objects.get(pk=sender_pk)
        self.receiver = get_object_or_404(get_user_model(), pk=receiver_pk)
        super(MessageForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Message
        fields = ['text']

    def clean(self):
        cleaned_data = super(MessageForm, self).clean()
        if self.sender == self.receiver:
            raise forms.ValidationError('You cannot send a message to yourself')
        return cleaned_data

source/webapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView, TemplateView, ListView, DetailView
from webapp.forms import MessageForm
from webapp.models import Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    template_name = 'messages/message_create.html'
    model = Message
    form_class = MessageForm

    def get_form_kwargs(self):
        kwargs = super(MessageCreateView, self).get_form_kwargs()
        receiver_pk = self.kwargs.get('pk')
        sender_pk = self.request.user.pk
        kwargs.update({
            'receiver_pk': receiver_pk,
            'sender_pk': sender_pk,
        })
        return kwargs

    def form_valid(self, form):
        message = form.save(commit=False)
        message.sender = self.request.user
        message.receiver = get_object_or_404(get_user_model(), pk=self.kwargs['pk'])
        message.save()
        return redirect('webapp:message_box')


class MessageBoxView(LoginRequiredMixin, TemplateView):
    template_name = 'messages/message_box.html'


class IncomingMessagesListView(LoginRequiredMixin, ListView):
    template_name = 'messages/message_inbox.html'
    model = Message
    context_object_name = 'messages'
    paginate_by = 5
    ordering = ['-id']

    def get_queryset(self):
        queryset = super(IncomingMessagesListView, self).get_queryset()
        queryset = queryset.filter(receiver=self.request.user)
        return queryset


class OutcomingMessagesListView(LoginRequiredMixin, ListView):
    template_name = 'messages/message_outbox.html'
    model = Message
    context_object_name = 'messages'
    paginate_by = 5
    ordering = ['-id']

    def get_queryset(self):
        queryset = super(OutcomingMessagesListView, self).get_queryset()
        queryset = queryset.filter(sender=self.request.user)
        return queryset


class MessageDetailView(UserPassesTestMixin, DetailView):
    template_name = 'messages/message_detail.html'
    model = Message

    def test_func(self):
        return self.request.user == self.get_object().sender or self.request.user == self.get_object().receiver

source/webapp/templates/messages/message_box.html
{% extends "base.html" %}
{% block title %}Messages{% endblock %}
{% block content %}
    <a class="btn btn-warning btn-lg btn-block my-5" href="{% url 'webapp:messages_incoming' %}">Incoming messages</a>
    <a class="btn btn-danger btn-lg btn-block" href="{% url 'webapp:messages_outcoming' %}">Outcoming messages</a>
{% endblock %}

source/webapp/templates/messages/message_create.html
{% extends "base.html" %}
{% block title %}New message{% endblock %}
{% block content %}
    <h1>New message</h1>
    {% include 'partial/form.html' with button_text='Send' form_method='post' %}
{% endblock %}

source/webapp/templates/messages/message_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Message{% endblock %}
{% block content %}
<div class="card bg-light mb-5">
    <div class="card-body">
            <p><b>From:</b> <a href="{% url 'accounts:detail' message.sender.pk %}">{{ message.sender.username }}</a><br>
            <p><b>To:</b> <a href="{% url 'accounts:detail' message.receiver.pk %}">{{ message.receiver.username }}</a><br>
            <p><b>Time: </b> {{ message.created_at }}<br></p>
            <p style="white-space:pre-line"><b>Text:</b> {{ message.text }}<br>
            <a class="btn btn-info btn-sm mt-3" href="{% url 'webapp:message_box' %}">Messenger</a>
    </div>
</div>
{% endblock %}

source/webapp/templates/messages/message_inbox.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Incoming messages{% endblock %}
{% block content %}
    <h2 class="my-3 text-md-center">Incoming messages</h2>
    {% for message in messages %}
        {% include 'partial/message_card.html' with is_receiver=True %}
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/messages/message_outbox.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Outcoming messages{% endblock %}
{% block content %}
    <h2 class="my-3 text-md-center">Outcoming messages</h2>
    {% if not messages %}
        <h3 class="my-3 text-center">You haven't sent any messages yet</h3>
    {% endif %}
    {% for message in messages %}
        {% include 'partial/message_card.html' with is_sender=True %}
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}