source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

source/api/urls.py
from django.urls import path
from .views import AddFriendView, UnFriendView

app_name = 'api'


urlpatterns = [
    path('user/<int:pk>/addfriend/', AddFriendView.as_view(), name='addfriend'),
    path('user/<int:pk>/unfriend/', UnFriendView.as_view(), name='unfriend'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import UserListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include('api.urls')),
    path('', UserListView.as_view(), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import MessageCreateView, MessageBoxView, IncomingMessagesListView, OutcomingMessagesListView,\
    MessageDetailView

app_name = 'webapp'


urlpatterns = [
    path('accounts/<int:pk>/messages/send/', MessageCreateView.as_view(), name='message_create'),
    path('messages/', MessageBoxView.as_view(), name='message_box'),
    path('messages/inbox/', IncomingMessagesListView.as_view(), name='messages_incoming'),
    path('messages/outbox/', OutcomingMessagesListView.as_view(), name='messages_outcoming'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
]

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='User')
    profile_pic = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Profile pic')

    def __str__(self):
        return self.user.username + "'s Profile"

source/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django import forms
from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name']


class UserChangeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name']


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="New password", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm password", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Current password", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords are not the same')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Old password is incorrect')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib.auth import login, get_user_model, update_session_auth_hash
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from accounts.models import Profile


class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user).save()
        login(self.request, user)
        return redirect('/')


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        form.save()
        profile_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserListView(ListView):
    template_name = 'user_list.html'
    model = get_user_model()
    context_object_name = 'user_list'
    paginate_by = 5
    ordering = ['-id']

source/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block title %}Edit personal data{% endblock %}

{% block menu_links %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:detail' user_obj.pk %}">Cancel</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:password_change' %}">Change password</a>
    </li>
{% endblock %}

{% block content %}
    <h1>Edit personal data</h1>
    <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <h1>Register</h1>
    {% include 'partial/form.html' with form_method='post' button_text="Sign up" %}
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load static %}
{% load friends %}
{% block title %}User page{% endblock %}

{% block nav %}
    {% if request.user.is_authenticated and request.user == user_obj %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change' user_obj.pk %}">Edit</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:password_change'  %}">Change password</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="media">
        {% if user_obj.profile.profile_pic %}
            <img src="{{ user_obj.profile.profile_pic.url }}" class="align-self-start mr-3" width="250" height="auto" alt="user picture">
        {% else %}
            <img src="{% static 'no_avatar.jpg' %}" class="align-self-start mr-3" width="250" height="auto" alt="user picture">
        {% endif %}
        <div class="media-body">
        <h4 class="mt-0 mb-3">Page of {{ user_obj.get_first_name|default:user_obj.username }}</h4>
        <p>Username: {{ user_obj.username }}</p>
        <p>Name: </p>
        <p>Last name: </p>
        {% if user.is_authenticated and user != user_obj %}
            {% with user_obj|is_friend:user as is_friend %}
                <a class="{% if is_friend %}hidden{% endif %} add-friend btn btn-success btn-sm mt-3" href="{% url 'api:addfriend' user_obj.pk %}">Add friend</a>
                <a class="{% if not is_friend %}hidden{% endif %} un-friend btn btn-danger btn-sm mt-3" href="{% url 'api:unfriend' user_obj.pk %}">Unfriend</a>
            {% endwith %}
            <a class="btn btn-info btn-sm mt-3 ml-3" href="{% url 'webapp:message_create' user_obj.pk %}">Send message</a>
        {% endif %}
        </div>
    </div>
    <hr>
    <h5 class="my-3">{{ user_obj.username }}'s friends:</h5>
    {% if user_obj.friends.all %}
        {% for friend in user_obj.friends.all %}
            {% include 'partial/user_card.html' with user_obj=friend.target_user %}
        {% endfor %}
        {% else %}
        <p>This user has no friends yet :/</p>
    {% endif %}
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/friends.js' %}"></script>
{% endblock %}

source/accounts/templates/user_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}User list{% endblock %}
{% block content %}
    <h2 class="my-3 text-md-center" id="user-list-headline">User list</h2>
    {% for user_obj in user_list %}
        {% include 'partial/user_card.html' %}
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/friends.js' %}"></script>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block menu_links %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:detail" user_obj.pk %}">Cancel</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:change" user_obj.pk %}">Edit</a>
    </li>
{% endblock %}

{% block content %}
    <h1>Change password</h1>
    {% url "accounts:password_change" as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" button_text='submit' %}
{% endblock %}