source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

source/api/urls.py
from django.urls import path
from .views import AddFriendView, UnFriendView

app_name = 'api'


urlpatterns = [
    path('user/<int:pk>/addfriend/', AddFriendView.as_view(), name='addfriend'),
    path('user/<int:pk>/unfriend/', UnFriendView.as_view(), name='unfriend'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import UserListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include('api.urls')),
    path('', UserListView.as_view(), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import MessageCreateView, MessageBoxView, IncomingMessagesListView, OutcomingMessagesListView,\
    MessageDetailView

app_name = 'webapp'


urlpatterns = [
    path('accounts/<int:pk>/messages/send/', MessageCreateView.as_view(), name='message_create'),
    path('messages/', MessageBoxView.as_view(), name='message_box'),
    path('messages/inbox/', IncomingMessagesListView.as_view(), name='messages_incoming'),
    path('messages/outbox/', OutcomingMessagesListView.as_view(), name='messages_outcoming'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Friend(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name='User', related_name='friends',
                             on_delete=models.CASCADE)
    target_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                    verbose_name='Friend')


class Message(models.Model):
    sender = models.ForeignKey(get_user_model(), verbose_name='Sender', related_name='messages',
                               on_delete=models.CASCADE)
    receiver = models.ForeignKey(get_user_model(), verbose_name='Receiver', on_delete=models.CASCADE)
    text = models.TextField(max_length=500, verbose_name='Text')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

source/webapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404

from webapp.models import Message


class MessageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        receiver_pk = kwargs.pop('receiver_pk')
        sender_pk = kwargs.pop('sender_pk')
        self.sender = get_user_model().objects.get(pk=sender_pk)
        self.receiver = get_object_or_404(get_user_model(), pk=receiver_pk)
        super(MessageForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Message
        fields = ['text']

    def clean(self):
        cleaned_data = super(MessageForm, self).clean()
        if self.sender == self.receiver:
            raise forms.ValidationError('You cannot send a message to yourself')
        return cleaned_data

source/webapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView, TemplateView, ListView, DetailView
from webapp.forms import MessageForm
from webapp.models import Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    template_name = 'messages/message_create.html'
    model = Message
    form_class = MessageForm

    def get_form_kwargs(self):
        kwargs = super(MessageCreateView, self).get_form_kwargs()
        receiver_pk = self.kwargs.get('pk')
        sender_pk = self.request.user.pk
        kwargs.update({
            'receiver_pk': receiver_pk,
            'sender_pk': sender_pk,
        })
        return kwargs

    def form_valid(self, form):
        message = form.save(commit=False)
        message.sender = self.request.user
        message.receiver = get_object_or_404(get_user_model(), pk=self.kwargs['pk'])
        message.save()
        return redirect('webapp:message_box')


class MessageBoxView(LoginRequiredMixin, TemplateView):
    template_name = 'messages/message_box.html'


class IncomingMessagesListView(LoginRequiredMixin, ListView):
    template_name = 'messages/message_inbox.html'
    model = Message
    context_object_name = 'messages'
    paginate_by = 5
    ordering = ['-id']

    def get_queryset(self):
        queryset = super(IncomingMessagesListView, self).get_queryset()
        queryset = queryset.filter(receiver=self.request.user)
        return queryset


class OutcomingMessagesListView(LoginRequiredMixin, ListView):
    template_name = 'messages/message_outbox.html'
    model = Message
    context_object_name = 'messages'
    paginate_by = 5
    ordering = ['-id']

    def get_queryset(self):
        queryset = super(OutcomingMessagesListView, self).get_queryset()
        queryset = queryset.filter(sender=self.request.user)
        return queryset


class MessageDetailView(UserPassesTestMixin, DetailView):
    template_name = 'messages/message_detail.html'
    model = Message

    def test_func(self):
        return self.request.user == self.get_object().sender or self.request.user == self.get_object().receiver

source/webapp/templates/partial/form.html
{% load widget_tweaks %}

{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}">
        {% csrf_token %}
{% endif %}

    {% for error in form.non_field_errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
    {% for field in form %}
            <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
            {% for error in field.errors %}
                <p class="form-error">{{ error }}</p>
            {% endfor %}
            <p>{{ field|add_class:'form-control' }}</p>
    {% endfor %}

{% if not fields_only %}
        <input class="btn btn-primary" type="submit" value="{{ button_text }}">
    </form>
{% endif %}

source/webapp/templates/partial/message_card.html
{% load staticfiles %}
<div class="card bg-light mb-5">
    <div class="card-body">
        {% if is_receiver == True %}
            <p><b>Sender:</b> <a href="{% url 'accounts:detail' message.sender.pk %}">{{ message.sender.username }}</a><br>
            <p><b>Received:</b> {{ message.created_at }}<br>
        {% elif is_sender == True %}
            <p><b>Receiver:</b> <a href="{% url 'accounts:detail' message.receiver.pk %}">{{ message.receiver.username }}</a><br>
            <p><b>Sent:</b> {{ message.created_at }}<br>
        {% endif %}
        <a class="btn btn-info btn-sm mt-3" href="{% url 'webapp:message_detail' message.pk %}">View message</a>
    </div>
</div>

source/webapp/templates/partial/pagination.html
<div class="d-flex justify-content-center mb-5">
    <div class="pagination mb-2">
        <span class="step-links">
            <a class="btn btn-primary" href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; First</a>
            {% if page_obj.has_previous %}
                <a class="btn btn-primary"  href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Back</a>
            {% else %}
                <span class="btn btn-secondary disabled" aria-disabled="true">Back</span>
            {% endif %}
            <form class="current-page" method="get">
                <label for="page">
                    {% if search %}<input type="hidden" name="search" value="{{ search }}">{% endif %}
                    <span class="mx-3">Page <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                    of {{ page_obj.paginator.num_pages }}</span>
                </label>
            </form>
            {% if page_obj.has_next %}
                <a class="btn btn-primary" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>
            {% else %}
                <span class="btn btn-secondary disabled" aria-disabled="true">Next</span>
            {% endif %}
            <a class="btn btn-primary" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        </span>
    </div>
</div>