source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

source/api/urls.py
from django.urls import path
from .views import AddFriendView, UnFriendView

app_name = 'api'


urlpatterns = [
    path('user/<int:pk>/addfriend/', AddFriendView.as_view(), name='addfriend'),
    path('user/<int:pk>/unfriend/', UnFriendView.as_view(), name='unfriend'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import UserListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include('api.urls')),
    path('', UserListView.as_view(), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import MessageCreateView, MessageBoxView, IncomingMessagesListView, OutcomingMessagesListView,\
    MessageDetailView

app_name = 'webapp'


urlpatterns = [
    path('accounts/<int:pk>/messages/send/', MessageCreateView.as_view(), name='message_create'),
    path('messages/', MessageBoxView.as_view(), name='message_box'),
    path('messages/inbox/', IncomingMessagesListView.as_view(), name='messages_incoming'),
    path('messages/outbox/', OutcomingMessagesListView.as_view(), name='messages_outcoming'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Friend(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name='User', related_name='friends',
                             on_delete=models.CASCADE)
    target_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                    verbose_name='Friend')


class Message(models.Model):
    sender = models.ForeignKey(get_user_model(), verbose_name='Sender', related_name='messages',
                               on_delete=models.CASCADE)
    receiver = models.ForeignKey(get_user_model(), verbose_name='Receiver', on_delete=models.CASCADE)
    text = models.TextField(max_length=500, verbose_name='Text')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

source/webapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404

from webapp.models import Message


class MessageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        receiver_pk = kwargs.pop('receiver_pk')
        sender_pk = kwargs.pop('sender_pk')
        self.sender = get_user_model().objects.get(pk=sender_pk)
        self.receiver = get_object_or_404(get_user_model(), pk=receiver_pk)
        super(MessageForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Message
        fields = ['text']

    def clean(self):
        cleaned_data = super(MessageForm, self).clean()
        if self.sender == self.receiver:
            raise forms.ValidationError('You cannot send a message to yourself')
        return cleaned_data

source/webapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView, TemplateView, ListView, DetailView
from webapp.forms import MessageForm
from webapp.models import Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    template_name = 'messages/message_create.html'
    model = Message
    form_class = MessageForm

    def get_form_kwargs(self):
        kwargs = super(MessageCreateView, self).get_form_kwargs()
        receiver_pk = self.kwargs.get('pk')
        sender_pk = self.request.user.pk
        kwargs.update({
            'receiver_pk': receiver_pk,
            'sender_pk': sender_pk,
        })
        return kwargs

    def form_valid(self, form):
        message = form.save(commit=False)
        message.sender = self.request.user
        message.receiver = get_object_or_404(get_user_model(), pk=self.kwargs['pk'])
        message.save()
        return redirect('webapp:message_box')


class MessageBoxView(LoginRequiredMixin, TemplateView):
    template_name = 'messages/message_box.html'


class IncomingMessagesListView(LoginRequiredMixin, ListView):
    template_name = 'messages/message_inbox.html'
    model = Message
    context_object_name = 'messages'
    paginate_by = 5
    ordering = ['-id']

    def get_queryset(self):
        queryset = super(IncomingMessagesListView, self).get_queryset()
        queryset = queryset.filter(receiver=self.request.user)
        return queryset


class OutcomingMessagesListView(LoginRequiredMixin, ListView):
    template_name = 'messages/message_outbox.html'
    model = Message
    context_object_name = 'messages'
    paginate_by = 5
    ordering = ['-id']

    def get_queryset(self):
        queryset = super(OutcomingMessagesListView, self).get_queryset()
        queryset = queryset.filter(sender=self.request.user)
        return queryset


class MessageDetailView(UserPassesTestMixin, DetailView):
    template_name = 'messages/message_detail.html'
    model = Message

    def test_func(self):
        return self.request.user == self.get_object().sender or self.request.user == self.get_object().receiver

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-5">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">SocialNet</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'accounts:detail' request.user.pk %}">Hello, {{ request.user.username }} <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'webapp:message_box' %}">Messenger <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Sign out <span class="sr-only">(current)</span></a>
                        </li>
                    {% else %}
                        <li class="nav-item active ml-3">
                            <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Sign in <span class="sr-only">(current)</span></a>
                        </li>
                    {% endif %}
                    {% block nav %}{% endblock %}
                </ul>
                {% block search %}{% endblock %}
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
<script src="{% static 'js/api_client.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>